services:
  server:
    image: rtrompier/netatmo-weather-server:latest
    environment:
      - NWS_VERBOSE=true
      - NWS_PORT=3000 # by default
      - NWS_LATITUDE=01.0000
      - NWS_LONGITUDE=02.0000
      - NWS_DISTANCE=2
    ports:
      - "3000:3000"